package template.main;

import template.algoritmos.HeapSort;
import template.algoritmos.BubbleSort;
import template.algoritmos.SelectionSort;
import template.algoritmos.MergeSort;
import template.algoritmos.InsertionSort;
import template.algoritmos.QuickSort;
import javax.swing.JOptionPane;
import template.algoritmos.ShellSort;

/**
 *
 * @author driog
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    private int numeroElementos;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Quadraticos = new javax.swing.JLabel();
        LinearesLogaritmos = new javax.swing.JLabel();
        SelectionSort = new javax.swing.JButton();
        InsertionSort = new javax.swing.JButton();
        BubbleSort = new javax.swing.JButton();
        QuickSort = new javax.swing.JButton();
        MergeSort = new javax.swing.JButton();
        HeapSort = new javax.swing.JButton();
        ShellSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simuladores Ordenação");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        Titulo.setText("Simuladores de Ordenação de Arrays");
        Titulo.setToolTipText("");

        Quadraticos.setText("Quadráticos");

        LinearesLogaritmos.setText("Lineares Logarítmos");

        SelectionSort.setText("Selection Sort");
        SelectionSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectionSortMouseClicked(evt);
            }
        });
        SelectionSort.addActionListener(this::SelectionSortActionPerformed);

        InsertionSort.setText("Insertion Sort");
        InsertionSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertionSortMouseClicked(evt);
            }
        });
        InsertionSort.addActionListener(this::InsertionSortActionPerformed);

        BubbleSort.setText("Bubble Sort");
        BubbleSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BubbleSortMouseClicked(evt);
            }
        });
        BubbleSort.addActionListener(this::BubbleSortActionPerformed);

        QuickSort.setText("Quick Sort");
        QuickSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuickSortMouseClicked(evt);
            }
        });
        QuickSort.addActionListener(this::QuickSortActionPerformed);

        MergeSort.setText("Merge Sort");
        MergeSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MergeSortMouseClicked(evt);
            }
        });
        MergeSort.addActionListener(this::MergeSortActionPerformed);

        HeapSort.setText("Heap Sort");
        HeapSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeapSortMouseClicked(evt);
            }
        });
        HeapSort.addActionListener(this::HeapSortActionPerformed);

        ShellSort.setText("ShellSort");
        ShellSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShellSortMouseClicked(evt);
            }
        });
        ShellSort.addActionListener(this::ShellSortActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SelectionSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MergeSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HeapSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(Quadraticos))
                            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(QuickSort, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(BubbleSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ShellSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InsertionSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LinearesLogaritmos)
                        .addGap(343, 343, 343))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(Quadraticos)
                .addGap(18, 18, 18)
                .addComponent(SelectionSort)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertionSort)
                    .addComponent(QuickSort))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BubbleSort)
                    .addComponent(ShellSort))
                .addGap(29, 29, 29)
                .addComponent(LinearesLogaritmos)
                .addGap(18, 18, 18)
                .addComponent(MergeSort)
                .addGap(18, 18, 18)
                .addComponent(HeapSort)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectionSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectionSortActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de elementos (10 a 50): " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 10 && quantidade <= 50 ) {
                numeroElementos = quantidade;
                SelectionSort ss = new SelectionSort( numeroElementos );
                ss.create();
            } else {
                JOptionPane.showMessageDialog( rootPane, "Digite um valor de 10 a 50" );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( rootPane, exc );
        }
    }//GEN-LAST:event_SelectionSortActionPerformed

    private void InsertionSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertionSortActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de elementos (10 a 50): " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 10 && quantidade <= 50 ) {
                numeroElementos = quantidade;
                InsertionSort is = new InsertionSort( numeroElementos );
                is.create();
            } else {
                JOptionPane.showMessageDialog( rootPane, "Digite um valor de 10 a 50" );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( rootPane, exc );
        }
    }//GEN-LAST:event_InsertionSortActionPerformed

    private void QuickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickSortActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de elementos (10 a 50): " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 10 && quantidade <= 50 ) {
                numeroElementos = quantidade;
                QuickSort qs = new QuickSort( numeroElementos );
                qs.create();
            } else {
                JOptionPane.showMessageDialog( rootPane, "Digite um valor de 10 a 50" );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( rootPane, exc );
        }
    }//GEN-LAST:event_QuickSortActionPerformed

    private void SelectionSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectionSortMouseClicked
        
    }//GEN-LAST:event_SelectionSortMouseClicked

    private void QuickSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuickSortMouseClicked
        
    }//GEN-LAST:event_QuickSortMouseClicked

    private void InsertionSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertionSortMouseClicked
        
    }//GEN-LAST:event_InsertionSortMouseClicked

    private void BubbleSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BubbleSortMouseClicked
        
    }//GEN-LAST:event_BubbleSortMouseClicked

    private void MergeSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MergeSortMouseClicked
       
    }//GEN-LAST:event_MergeSortMouseClicked

    private void HeapSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeapSortMouseClicked
        
    }//GEN-LAST:event_HeapSortMouseClicked

    private void BubbleSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubbleSortActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de elementos (10 a 50): " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 10 && quantidade <= 50 ) {
                numeroElementos = quantidade;
                BubbleSort bs = new BubbleSort( numeroElementos );
                bs.create();
            } else {
                JOptionPane.showMessageDialog( rootPane, "Digite um valor de 10 a 50" );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( rootPane, exc );
        }
    }//GEN-LAST:event_BubbleSortActionPerformed

    private void MergeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MergeSortActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de elementos (10 a 50): " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 10 && quantidade <= 50 ) {
                numeroElementos = quantidade;
                MergeSort ms = new MergeSort( numeroElementos );
                ms.create();
            } else {
                JOptionPane.showMessageDialog( rootPane, "Digite um valor de 10 a 50" );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( rootPane, exc );
        }
    }//GEN-LAST:event_MergeSortActionPerformed

    private void HeapSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeapSortActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de elementos (10 a 50): " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 10 && quantidade <= 50 ) {
                numeroElementos = quantidade;
                HeapSort hs = new HeapSort( numeroElementos );
                hs.create();
            } else {
                JOptionPane.showMessageDialog( rootPane, "Digite um valor de 10 a 50" );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( rootPane, exc );
        }
    }//GEN-LAST:event_HeapSortActionPerformed

    private void ShellSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShellSortMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ShellSortMouseClicked

    private void ShellSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShellSortActionPerformed
        try{
            String valor = JOptionPane.showInputDialog( "Quantidade de elementos (10 a 50): " );
            int quantidade = Integer.parseInt( valor );
            if( quantidade >= 10 && quantidade <= 50 ) {
                numeroElementos = quantidade;
                ShellSort ss = new ShellSort( numeroElementos );
                ss.create();
            } else {
                JOptionPane.showMessageDialog( rootPane, "Digite um valor de 10 a 50" );
            }
        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( rootPane, exc );
        }
    }//GEN-LAST:event_ShellSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BubbleSort;
    private javax.swing.JButton HeapSort;
    private javax.swing.JButton InsertionSort;
    private javax.swing.JLabel LinearesLogaritmos;
    private javax.swing.JButton MergeSort;
    private javax.swing.JLabel Quadraticos;
    private javax.swing.JButton QuickSort;
    private javax.swing.JButton SelectionSort;
    private javax.swing.JButton ShellSort;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}